version: '3.8'
 
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/eiserproject
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=eiser
      - DB_USER=root
      - DB_PASSWORD=3306  # Match MYSQL_ROOT_PASSWORD in db service

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: eiser
      MYSQL_ROOT_PASSWORD: 3306  # Ensure the root password is properly set
 
volumes:
  mysql_data:
