# Generated by Django 5.1.3 on 2025-01-14 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.coupon'),
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Initiated', 'Initiated'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.signup')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.checkout')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coupon_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted')], default='Pending', max_length=20)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eiserapp.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.signup')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.order'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.checkout')),
            ],
        ),
    ]
