# Generated by Django 5.1.3 on 2025-01-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0002_alter_appliedcoupon_coupon_checkout_deliverydetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eiserapp.cart'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
