# Generated by Django 5.1.3 on 2025-01-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0004_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcoupon',
            name='status',
            field=models.CharField(choices=[('NotApplied', 'NotApplied'), ('Applied', 'Applied'), ('Used', 'Used')], default='NotApplied', max_length=20),
        ),
    ]
