# Generated by Django 5.1.3 on 2025-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0006_remove_checkout_cart_checkout_cart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
