# Generated by Django 5.1.3 on 2025-01-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0008_returneditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditems',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eiserapp.deliverydetails'),
            preserve_default=False,
        ),
    ]
