# Generated by Django 5.1.3 on 2025-01-17 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0010_alter_returneditems_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.signup')),
            ],
        ),
    ]
