# Generated by Django 5.1.3 on 2025-01-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0013_deliveryboy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='id_proof',
            field=models.FileField(upload_to='delivery_boy_ids/'),
        ),
    ]
