# Generated by Django 5.1.3 on 2025-01-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0014_alter_deliveryboy_id_proof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryboy',
            options={'ordering': ['-date'], 'verbose_name': 'Delivery Boy', 'verbose_name_plural': 'Delivery Boys'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ['-date'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='dboy_photos/'),
        ),
    ]
