# Generated by Django 5.1.3 on 2025-01-22 07:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0015_alter_deliveryboy_options_alter_signup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAssignDeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.deliveryboy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.orderitem')),
            ],
        ),
    ]
