# Generated by Django 5.1.3 on 2025-01-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0016_orderassigndeliveryboy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-checkout'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
