# Generated by Django 5.1.3 on 2025-01-27 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0017_alter_orderitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainttoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('dboy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eiserapp.deliveryboy')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eiserapp.seller')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eiserapp.signup')),
            ],
        ),
    ]
