# Generated by Django 5.1.3 on 2025-01-27 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0018_complainttoadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complainttoadmin',
            options={'ordering': ['-date'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AddField(
            model_name='complainttoadmin',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
