# Generated by Django 5.1.3 on 2025-01-27 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0019_alter_complainttoadmin_options_complainttoadmin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eiserapp.login')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='ComplainttoAdmin',
        ),
    ]
