# Generated by Django 5.1.3 on 2025-01-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0021_alter_contact_options_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.FileField(default=1, upload_to='category_thumbs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='thumbnail',
            field=models.FileField(default=1, upload_to='subcategory_thumbs/'),
            preserve_default=False,
        ),
    ]
