# Generated by Django 5.1.3 on 2025-01-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0023_remove_subcategory_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='thumbnail',
            field=models.FileField(default=1, upload_to='subcategory_thumbs/'),
            preserve_default=False,
        ),
    ]
