# Generated by Django 5.1.3 on 2025-02-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0024_subcategory_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
