# Generated by Django 5.1.3 on 2025-02-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiserapp', '0026_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='otp_cooldown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
